Controllers/AdresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DBMS.Controllers
{
    [Authorize]
    public class AdresController : Controller
    {
        DataEntities db = new DataEntities();
        [HttpGet]
        public ActionResult Ekle()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Ekle(Adres adres)
        {
            int kullaniciID = Int32.Parse((string)Session["kullaniciID"]);
            adres.KullaniciID = kullaniciID;
            db.Adres.Add(adres);
            db.SaveChanges();
            return RedirectToAction("Index","Kullanici");
        }
        [HttpGet]
        [Route("Adres/Guncelle/{adresID}")]
        public ActionResult GuncelleGet(int adresID)
        {
            var model = db.Adres.Find(adresID);
            return View(model);
        }
        [HttpPost]
        public ActionResult GuncellePost(Adres adres)
        {
            var model = db.Adres.Find(adres.AdresID);
            model.Sehir = adres.Sehir;
            model.Ilce = adres.Ilce;
            model.Cadde_Sokak = adres.Cadde_Sokak;
            model.Numara = adres.Numara;
            db.SaveChanges();
            return RedirectToAction("Index", "Kullanici");
        }
        [Route("Adres/Sil/{adresID}")]
        public ActionResult Sil(int adresID)
        {
            var model = db.Adres.Find(adresID);
            db.Adres.Remove(model);
            db.SaveChanges();
            return RedirectToAction("Index", "Kullanici");
        }
    }
}

Views/Adres/Ekle.cshtml
@model Adres
@{
    ViewBag.Title = "Ekle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Ekle</h2>

@using (Html.BeginForm("Ekle", "Adres", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(m => m.Sehir)
        @Html.TextBoxFor(m => m.Sehir, new { @class = "form-control" })

    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Ilce)
        @Html.TextBoxFor(m => m.Ilce, new { @class = "form-control" })

    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Cadde_Sokak)
        @Html.TextBoxFor(m => m.Cadde_Sokak, new { @class = "form-control" })

    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Numara)
        @Html.TextBoxFor(m => m.Numara, new { @class = "form-control" })

    </div>
    <br />
    <button class="btn btn-info">Ekle</button>



}

Views/Adres/GuncelleGet.cshtml
@model Adres
@{
    ViewBag.Title = "GuncelleGet";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Guncelle</h2>

@using (Html.BeginForm("GuncellePost", "Adres", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(m => m.Sehir)
        @Html.TextBoxFor(m => m.Sehir, new { @class = "form-control" })

    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Ilce)
        @Html.TextBoxFor(m => m.Ilce, new { @class = "form-control" })

    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Cadde_Sokak)
        @Html.TextBoxFor(m => m.Cadde_Sokak, new { @class = "form-control" })

    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Numara)
        @Html.TextBoxFor(m => m.Numara, new { @class = "form-control" })

    </div>

    <br />
    @Html.HiddenFor(m => m.AdresID)
    <button type="submit" class="btn btn-warning">Güncelle</button>



}