ViewModels/CuzdanViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DBMS.ViewModels
{
    public class CuzdanViewModel
    {
        public Musteri Musteri { get; set; }
        public Kullanici Kullanici { get; set; }
        public List<KrediKarti> KrediKartlari { get; set; }
    }
}

ViewModels/KullaniciViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DBMS.ViewModels
{
    public class KullaniciViewModel
    {
        public Kullanici Kullanici { get; set; }
        public List<Email> Emailler { get; set; }
        public List<KrediKarti> KrediKartlari { get; set; }
        public List<Adres> Adresler { get; set; }


    }
}

Controllers/EmailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DBMS.Controllers
{
    [Authorize]
    public class EmailController : Controller
    {
        DataEntities db = new DataEntities();
        public ActionResult Index()
        {
            return View();
        }
        
        
        public ActionResult Sil(string email)
        { 
            var model = db.Email.Find(email);
            db.Email.Remove(model);
            db.SaveChanges();
            return RedirectToAction("Index", "Kullanici");

        }
        [HttpGet]
        public ActionResult Ekle()
        { 
            return View();
        }
        [HttpPost]
        public ActionResult Ekle(string email)
        {
            int kullaniciID = Int32.Parse((string)Session["kullaniciID"]);
            Email email1 = new Email()
            {
                Email1 = email,
                KullaniciID = kullaniciID

            };
            db.Email.Add(email1);
            db.SaveChanges();
            return RedirectToAction("Index", "Kullanici");
        }

    }
}

Controllers/KullaniciController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DBMS.ViewModels;
namespace DBMS.Controllers
{
    [Authorize]
    public class KullaniciController : Controller
    {
       
        DataEntities db = new DataEntities();
        
        public ActionResult Index()
        {
            int kullaniciID = Int32.Parse((string)Session["kullaniciID"]);
            KullaniciViewModel kullaniciViewModel = new KullaniciViewModel
            {
                Kullanici = db.Kullanici.Find(kullaniciID),
                Adresler = db.Adres.Where(x=>x.KullaniciID ==kullaniciID).ToList(),
                Emailler = db.Email.Where(x => x.KullaniciID == kullaniciID).ToList(),
                KrediKartlari = db.KrediKarti.Where(x => x.KullaniciID == kullaniciID).ToList()

            };
            return View(kullaniciViewModel);
        }
       
        
        [HttpGet]
        [Route("Kullanici/GuncelleGet/{kullaniciID}")]
        public ActionResult GuncelleGet(int kullaniciID)
        {
            var model = db.Kullanici.Find(kullaniciID);
            return View(model);
        }

        [HttpPost]
        
        public ActionResult GuncellePost(Kullanici kullanici)
        {
            var model = db.Kullanici.Find(kullanici.KullaniciID);
            model.Ad = kullanici.Ad;
            model.Soyad = kullanici.Soyad;
            model.Sifre = kullanici.Sifre;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [Authorize]
        public ActionResult Cuzdan()
        {
            int kullaniciID = Int32.Parse((string)Session["kullaniciID"]);
            CuzdanViewModel cuzdanViewModel = new CuzdanViewModel()
            {

                Musteri = db.Musteri.Find(kullaniciID),
                Kullanici=db.Kullanici.Find(kullaniciID),
                KrediKartlari = db.KrediKarti.Where(x => x.KullaniciID == kullaniciID).ToList()

            };
            return View(cuzdanViewModel);
        }
        [HttpGet]
        public ActionResult KrediKartiEkle()
        {
            return View();
        }
       
        [HttpPost]
        public ActionResult KrediKartiEkle(decimal KrediKartiNo)
        {
            int kullaniciID = Int32.Parse((string)Session["kullaniciID"]);
            KrediKarti krediKarti = new KrediKarti()
            {
                KrediKarti1 = KrediKartiNo,
                KullaniciID = kullaniciID
            };
            db.KrediKarti.Add(krediKarti);
            db.SaveChanges();
            return RedirectToAction("Cuzdan", "Kullanici");
        }
        public ActionResult KrediKartiSil(decimal KrediKartiNo)
        {
            var model = db.KrediKarti.Find(KrediKartiNo);
            db.KrediKarti.Remove(model);
            db.SaveChanges();
            return RedirectToAction("Cuzdan", "Kullanici");
        }
        public ActionResult HesabimiSil(int id)
        {
            var model = db.Kullanici.Find(id);
            db.Kullanici.Remove(model);
            db.SaveChanges();
            return RedirectToAction("Logout", "Login");
        }
    }
}

Views/Kullanici/Cuzdan.cshtml
@model DBMS.ViewModels.CuzdanViewModel
@{
    ViewBag.Title = "Cuzdan";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Cüzdanım</h2>

<table class="table table-light">
    <tr>
        <th>Ad</th>
        <th>Soyad</th>
        <th>Bakiye</th>
        <th>Puan</th>
    </tr>
    <tr>

        <td>@Model.Kullanici.Ad</td>
        <td>@Model.Kullanici.Soyad</td>
        <td>@Model.Musteri.Bakiye</td>
        <td>@Model.Musteri.Puan</td>

    </tr>

</table>
<br />
<h4>Kredi Kartlarım</h4>

<table class="table table-light">
    <tr>
        <th>Kredi Kartı Numarası</th>
        <th>Sil</th>

    </tr>
    @foreach (var item in Model.KrediKartlari)
    {
        <tr>
            <td>@item.KrediKarti1</td>
            <td>
                @using (Html.BeginForm("KrediKartiSil", "Kullanici", FormMethod.Post))
                {
                    <div style="display:none" class="form-group">
                       
                        <input class="form-control" type="text" name="KrediKartiNo" value="@item.KrediKarti1" />

                    </div>

                    <button style="display:inline" class="btn btn-danger">Sil</button>
                }

            </td>
        </tr>
    }


</table>
<a class="btn btn-success" href="/Kullanici/KrediKartiEkle">Ekle</a>

Views/Kullanici/GuncelleGet.cshtml
@model Kullanici
@{
    ViewBag.Title = "Guncelle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Güncelle</h2>
@using (Html.BeginForm("GuncellePost","Kullanici",FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(m =>m.Ad)
        @Html.TextBoxFor(m => m.Ad, new { @class = "form-control" })

    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Soyad)
        @Html.TextBoxFor(m => m.Soyad, new { @class = "form-control" })

    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Sifre)
        @Html.TextBoxFor(m => m.Sifre, new { @class = "form-control" })

    </div>
   
    <br />
    @Html.HiddenFor(m=>m.KullaniciID)
    <button type="submit"  class="btn btn-warning">Güncelle</button>



}

Views/Kullanici/Index.cshtml
@model DBMS.ViewModels.KullaniciViewModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Profilim</h2>

<table class="table" id="tblHesap">
    <tr>
        <th>Ad</th>
        <th>Soyad</th>
        <th>Sifre</th>
        <th>Yetki</th>
        <th>Güncelle</th>
        <th>Hesabı Sil</th>
    </tr>
    <tr>
        <td>@Model.Kullanici.Ad</td>
        <td>@Model.Kullanici.Soyad</td>
        <td>@Model.Kullanici.Sifre</td>
        <td>
            Normal Kullanıcı
        </td>
        <td><a class="btn btn-warning" href="/Kullanici/GuncelleGet/@Model.Kullanici.KullaniciID">Güncelle</a></td>
        <td><a class="btn btn-danger btnHesapSil" data-id="@Model.Kullanici.KullaniciID">Hesabımı Sil</a></td>
    </tr>
</table>

<h4 class="mt-5">Adreslerim</h4>

<table class="table">
    <tr>
        <th>Şehir</th>
        <th>İlçe</th>
        <th>Cadde/Sokak</th>
        <th>Numara</th>
        <th>Güncelle</th>
        <th>Sil</th>
    </tr>
    @foreach (var item in Model.Adresler)
    {
        <tr>
            <td>@item.Sehir</td>
            <td>@item.Ilce</td>
            <td>@item.Cadde_Sokak</td>
            <td>@item.Numara</td>
            <td><a class="btn btn-warning" href="/Adres/Guncelle/@item.AdresID">Güncelle</a></td>
            <td><a class="btn btn-danger" href="/Adres/Sil/@item.AdresID">Sil</a></td>
        </tr>
    }

</table>
<a href="/Adres/Ekle" class="btn btn-success">Ekle</a>



<h4 class="mt-5">Emaillerim</h4>

<table class="table">
    <tr>
        <th>Email</th>
        <th>Sil</th>

    </tr>
    @foreach (var item in Model.Emailler)
    {
        <tr>
            <td>@item.Email1</td>
            <td>
               
                    @using (Html.BeginForm("Sil", "Email", FormMethod.Post))
                    {
                        <div style="display:none" class="form-group">
                            @Html.Label("Email")
                            <input class="form-control" type="text" name="email" value="@item.Email1" />

                        </div>

                        <button style="display:inline" class="btn btn-danger">Sil</button>
                    }
                

                



            </td>
        </tr>
    }

</table>
<a href="/Email/Ekle" class="btn btn-success">Ekle</a>

<div style="padding-top:300px"></div>

Views/Kullanici/KrediKartiEkle.cshtml
@{
    ViewBag.Title = "KrediKartiEkle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>KrediKartiEkle</h2>

@using (Html.BeginForm("KrediKartiEkle", "Kullanici", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Kredi Kartı Numarası")
        <input class="form-control" type="text" name="KrediKartiNo" />

    </div>
    <br />
    <button type="submit" class="btn btn-warning">Ekle</button>
}